apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splunk-ai-operator.serviceAccountName" . }}
  namespace: {{ include "splunk-ai-operator.namespace" . }}
  labels:
{{- include "splunk-ai-operator.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.annotations | nindent 4 }}
