---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ai-splunk-com-v1-aiplatform
  failurePolicy: Fail
  name: maiplatform-v1.kb.io
  rules:
  - apiGroups:
    - ai.splunk.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - aiplatforms
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-ai-splunk-com-v1-aiservice
  failurePolicy: Fail
  name: maiservice-v1.kb.io
  rules:
  - apiGroups:
    - ai.splunk.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - aiservices
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ai-splunk-com-v1-aiplatform
  failurePolicy: Fail
  name: vaiplatform-v1.kb.io
  rules:
  - apiGroups:
    - ai.splunk.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - aiplatforms
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ai-splunk-com-v1-aiservice
  failurePolicy: Fail
  name: vaiservice-v1.kb.io
  rules:
  - apiGroups:
    - ai.splunk.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - aiservices
  sideEffects: None
