# Default values for splunk-ai.
# This is a YAML-formatted file.
# Users can override these (e.g. via --values) to configure both the CR and the Ingress.

# Metadata overrides:
nameOverride: ""
fullnameOverride: ""

# Storage volume
volume:
  # Remote volume URI in the format s3://bucketname/<path prefix>
  path: ""
  # Optional override endpoint (only really needed for S3-compatible like MinIO)
  endpoint: ""
  # Region of the remote storage volume where apps reside. Used for aws, if provided. Not used for minio and azure.
  region: ""
  # Secret object name
  secretRef: ""

# Name of service account to use for the AIPlatform CR
serviceAccountName: ""

# List of defined features to enable in the AI platform (e.g., saia) and version
features:
  - name: ""
    # Name of service account to use for the AI feature CR
    serviceAccountName: ""
    # Version of the feature
    version: ""

sidecars:
  # Enables the Envoy sidecar
  envoy: true
  # Enables the Fluent Bit sidecar
  fluentBit: true
  # Enables the OpenTelemetry collector sidecar
  otel: true
  # Enables the Prometheus Operator sidecar
  prometheusOperator: true

# TLS cert secret managed by cert-manager
certificateRef: ""
# Internal cluster DNS suffix
clusterDomain: "cluster.local"

# List of image registries to use for Ray
images:
  # Image for SAIA
  saiaImage: "splunkai/saia:latest"
  # Image for Weaviate
  weaviateImage: "docker.io/weaviate:latest"
  # Image for Ray head group
  rayHeadGroupImage: "rayproject/ray-head:latest"
  # Image for Ray worker group
  rayWorkerGroupImage: "rayproject/ray-worker:latest"

defaultAcceleratorType: "LS04S"  # e.g. "L40S", "LS04S", "A10G", "A100", "V100"

splunkConfiguration:
  # Name of the SplunkConfiguration instance
  crName: "splunk-standalone"
  # Namespace of the SplunkConfiguration instance
  crNamespace: "default"
  # Splunk secret reference
  secretRef:
    name: "splunk-secret"
    namespace: "default"
  endpoint: "https://splunk.default.svc.cluster.local:8089"
  # Optional, if not using secretRef
  token: "splunk-token"

# specifies object storage for AI artifacts (e.g., S3 or GCS bucket)
storage:
  vectorDB:
    # Optional name of an existing PVC to use
    pvcName: ""
    # Size of the volume to create if PVCName is not provided
    size: "100Gi"  # e.g., "100Gi", "1Ti"
    # Optional StorageClassName to use for dynamic PVC provisioning
    storageClassName: ""  # e.g., "gp2", "standard", "azurefile"

gpuScheduling:
  # controls GPU node placement for Ray workloads
  nodeSelector: {}
  # affinity for GPU/CPU nodes
  affinity: {}
  # required if GPU nodes are tainted
  tolerations: []

cpuScheduling:
  # controls CPU node placement for CPU workloads
  nodeSelector: {}
  # affinity for CPU nodes
  affinity: {}
  # required if CPU nodes are tainted
  tolerations: []

# ingress settings (fully optional)
ingress:
  enabled: false
  className: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
