---
apiVersion: v2
name: splunk-operator
description: A Helm chart for deploying the Splunk AI Operator
type: application
icon: https://example.com/icon.png
keywords:
  - splunk
  - ai
  - kuberay
home: https://github.com/splunk/splunk-ai-operator
sources:
  - https://github.com/splunk/splunk-ai-operator
maintainers:
  - name: Splunk AI Team
    email: splunkai@cisco.com

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: "0.1.0"

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"
