# Add labels to Splunk AI Operator deployment
labels: {}

# Add annotations to Splunk AI Operator deployment
annotations: {}

# Add pod annotations to Splunk AI Operator deployment pod
podAnnotations: {}

# Add pod labels to Splunk AI Operator deployment pod
podLabels: {}

# Set security context for Splunk Operator pod
# reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#podsecuritycontext-v1-core
securityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Splunk AI Operator image and pull policy
# reference: https://github.com/splunk/splunk-ai-operator
image:
  repository: controller:latest
  pullPolicy: IfNotPresent

# Define liveness probe to check if manager container is running
# reference: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#types-of-probe
livenessProbe:
  httpGet:
    path: /healthz
    port: 8081
  initialDelaySeconds: 15
  periodSeconds: 20

# Define readiness probe to check if manager container is ready for requests
# reference: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#types-of-probe
readinessProbe:
  httpGet:
    path: /readyz
    port: 8081
  initialDelaySeconds: 5
  periodSeconds: 10

# Set resource requests and limits for manager container
resources:
  limits:
    cpu: 1000m
    memory: 2000Mi
  requests:
    cpu: 1000m
    memory: 2000Mi

# Specify volume mounts for the manager container, append additional volume mounts to list
# reference: https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/
volumeMounts: []
# - mountPath:
#   name:

# Specify volumes for Splunk AI Operator pod, append additional volumes to list
# reference: https://kubernetes.io/docs/concepts/storage/volumes/
volumes: []
# - name:
#   persistentVolumeClaim:
#     claimName:

# Set duration in seconds the pod needs to terminate gracefully
# reference: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#pod-v1-core
terminationGracePeriodSeconds: 10
