---
apiVersion: v2
name: splunk-ai-platform
description: A Helm chart for deploying Splunk AIPlatform custom resources
type: application
version: 0.1.0
appVersion: "v4.0.0"
icon: https://example.com/icon.png
keywords:
  - splunk
  - ai
  - kuberay
home: https://github.com/splunk/splunk-ai-operator
sources:
  - https://github.com/splunk/splunk-ai-operator
maintainers:
  - name: Splunk AI Team
    email: splunkai@cisco.com
dependencies:
  - name: splunk-ai-operator
    version: "0.1.0"
    repository: "file://../splunk-ai-operator"
    condition: splunk-ai-operator.enabled
  - name: kuberay-operator
    version: "1.3.2"
    repository: "https://ray-project.github.io/kuberay-helm"
    condition: kuberay-operator.enabled
  - name: cert-manager
    version: "1.18.0"
    repository: "https://charts.jetstack.io"
    condition: cert-manager.enabled
  - name: prometheus
    version: "27.20.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled
  - name: opentelemetry-collector
    version: "0.126.0"
    repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
    condition: opentelemetry-collector.enabled
