apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
{{- include "splunk-ai-operator.labels" . | nindent 4 }}
  name: {{ include "splunk-ai-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "splunk-ai-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "splunk-ai-operator.fullname" . }}-controller-manager
  namespace: {{ include "splunk-ai-operator.namespace" . }}
