apiVersion: ai.splunk.com/v1
kind: AIPlatform
metadata:
  labels:
    app.kubernetes.io/name: splunk-ai-operator
    app.kubernetes.io/managed-by: kustomize
  name: aiplatform-sample
spec:
  # TODO(user): Add fields here
