apiVersion: kuttl.dev/v1beta1
kind: TestSuite
commands:
  - command: helm repo add splunk https://splunk.github.io/splunk-operator/
testDirs:
- ./tests/helm
parallel: 1
timeout: 600
startKIND: false
artifactsDir: kuttl-artifacts
kindNodeCache: false
