# templates/aiplatform.yaml
{{- if .Capabilities.APIVersions.Has "v4.splunkai/v1" -}}
apiVersion: v4.splunkai/v1
kind: AIPlatform
metadata:
  name: {{ include "splunk-ai-platform.fullname" . }}
  namespace: {{ include "splunk-ai-platform.namespace" . }}
  labels:
    {{- include "splunk-ai-platform.labels" . | nindent 4 }}
spec:
  objectStorage:
    path: {{ .Values.objectStorage.path | quote }}
    {{- if .Values.objectStorage.endpoint }}
    endpoint: {{ .Values.objectStorage.endpoint | quote }}
    {{- end }}
    region: {{ .Values.objectStorage.region | quote }}
    secretRef: {{ .Values.objectStorage.secretRef | quote }}
  {{- if .Values.serviceAccountName}}
  serviceAccountName: {{ .Values.serviceAccountName | quote }}
  {{- end }}
  features:
    {{- range .Values.features }}
    - name: {{ .name | quote }}
      serviceAccountName: {{ .serviceAccountName | quote }}
      version: {{ .version | quote }}
    {{- end }}
  headGroupSpec:
    serviceAccountName: {{ .Values.headGroupSpec.serviceAccountName | quote }}
    nodeSelector: {{ toYaml .Values.headGroupSpec.nodeSelector | nindent 4 }}
    affinity: {{ toYaml .Values.headGroupSpec.affinity | nindent 4 }}
    tolerations: {{ toYaml .Values.headGroupSpec.tolerations | nindent 4 }}
    imageRegistry: {{ .Values.headGroupSpec.imageRegistry | quote }}
  workerGroupSpec:
    serviceAccountName: {{ .Values.workerGroupSpec.serviceAccountName | quote }}
    imageRegistry: {{ .Values.workerGroupSpec.imageRegistry | quote }}
    gpuConfigs:
      {{- range .Values.workerGroupSpec.gpuConfigs }}
      - tier: {{ .tier | quote }}
        minReplicas: {{ .minReplicas }}
        maxReplicas: {{ .maxReplicas }}
        gpusPerPod: {{ .gpusPerPod }}
        resources:
{{- toYaml .resources | nindent 12 }}
      {{- end }}
    nodeSelector: {{ toYaml .Values.workerGroupSpec.nodeSelector | nindent 4 }}
    affinity: {{ toYaml .Values.workerGroupSpec.affinity | nindent 4 }}
    tolerations: {{ toYaml .Values.workerGroupSpec.tolerations | nindent 4 }}
  sidecars:
    envoy: {{ .Values.sidecars.envoy }}
    fluentBit: {{ .Values.sidecars.fluentBit }}
    otel: {{ .Values.sidecars.otel }}
    prometheusOperator: {{ .Values.sidecars.prometheusOperator }}
  certificateRef: {{ .Values.certificateRef | quote }}
  clusterDomain: {{ .Values.clusterDomain | quote }}
  images:
    saiaImage: {{ .Values.images.saiaImage | quote }}
    weaviateImage: {{ .Values.images.weaviateImage | quote }}
    rayHeadGroupImage: {{ .Values.images.rayHeadGroupImage | quote }}
    rayWorkerGroupImage: {{ .Values.images.rayWorkerGroupImage | quote }}
  defaultAcceleratorType: {{ .Values.defaultAcceleratorType | quote }}
  splunkConfiguration: {{ toYaml .Values.splunkConfiguration | nindent 4 }}
  storage:
    vectorDB:
      pvcName: {{ .Values.storage.vectorDB.pvcName | quote }}
      size: {{ .Values.storage.vectorDB.size | quote }}
      storageClassName: {{ .Values.storage.vectorDB.storageClassName | quote }}
  gpuScheduler:
    nodeSelector: {{ toYaml .Values.gpuScheduler.nodeSelector | nindent 4 }}
    affinity: {{ toYaml .Values.gpuScheduler.affinity | nindent 4 }}
    tolerations: {{ toYaml .Values.gpuScheduler.tolerations | nindent 4 }}
  cpuScheduler:
    nodeSelector: {{ toYaml .Values.cpuScheduler.nodeSelector | nindent 4 }}
    affinity: {{ toYaml .Values.cpuScheduler.affinity | nindent 4 }}
    tolerations: {{ toYaml .Values.cpuScheduler.tolerations | nindent 4 }}
{{- end -}}
