# templates/aiplatform.yaml
apiVersion: ai.splunk.com/v1
kind: AIPlatform
metadata:
  name: {{ include "splunk-ai-platform.fullname" . }}
  namespace: {{ include "splunk-ai-platform.namespace" . }}
  labels:
{{- include "splunk-ai-platform.labels" . | nindent 4 }}
spec:
  objectStorage:
    path: {{ .Values.objectStorage.path | quote }}
{{- if .Values.objectStorage.endpoint }}
    endpoint: {{ .Values.objectStorage.endpoint | quote }}
{{- end }}
    region: {{ .Values.objectStorage.region | quote }}
    secretRef: {{ .Values.objectStorage.secretRef | quote }}
{{- if .Values.serviceAccountName}}
  serviceAccountName: {{ .Values.serviceAccountName | quote }}
{{- end }}
  features:
{{- range .Values.features }}
    - name: {{ .name | quote }}
      serviceAccountName: {{ .serviceAccountName | quote }}
      version: {{ .version | quote }}
{{- end }}
  headGroupSpec:
    serviceAccountName: {{ .Values.headGroupSpec.serviceAccountName | quote }}
{{- if .Values.headGroupSpec.nodeSelector }}
    nodeSelector: {{ toYaml .Values.headGroupSpec.nodeSelector | nindent 6 }}
{{- end }}
{{- if .Values.headGroupSpec.affinity }}
    affinity: {{ toYaml .Values.headGroupSpec.affinity | nindent 6 }}
{{- end }}
{{- if .Values.headGroupSpec.tolerations }}
    tolerations: {{ toYaml .Values.headGroupSpec.tolerations | nindent 6 }}
{{- end }}
    imageRegistry: {{ .Values.headGroupSpec.imageRegistry | quote }}
  workerGroupSpec:
    serviceAccountName: {{ .Values.workerGroupSpec.serviceAccountName | quote }}
    imageRegistry: {{ .Values.workerGroupSpec.imageRegistry | quote }}
{{- if .Values.workerGroupSpec.gpuConfigs }}
    gpuConfigs:
{{- range .Values.workerGroupSpec.gpuConfigs }}
      - tier: {{ .tier | quote }}
        minReplicas: {{ .minReplicas }}
        maxReplicas: {{ .maxReplicas }}
        gpusPerPod: {{ .gpusPerPod }}
        resources:
{{- toYaml .resources | nindent 10 }}
{{- end }}
{{- if .Values.workerGroupSpec.nodeSelector }}
    nodeSelector: {{ toYaml .Values.workerGroupSpec.nodeSelector | nindent 6 }}
{{- end }}
{{- if .Values.workerGroupSpec.affinity }}
    affinity: {{ toYaml .Values.workerGroupSpec.affinity | nindent 6 }}
{{- end }}
{{- if .Values.workerGroupSpec.tolerations }}
    tolerations: {{ toYaml .Values.workerGroupSpec.tolerations | nindent 6 }}
{{- end }}
{{- end }}
  sidecars:
    envoy: {{ .Values.sidecars.envoy }}
    fluentBit: {{ .Values.sidecars.fluentBit }}
    otel: {{ .Values.sidecars.otel }}
    prometheusOperator: {{ .Values.sidecars.prometheusOperator }}
  certificateRef: {{ .Values.certificateRef | quote }}
  clusterDomain: {{ .Values.clusterDomain | quote }}
  images:
    saiaImage: {{ .Values.images.saiaImage | quote }}
    weaviateImage: {{ .Values.images.weaviateImage | quote }}
    rayHeadGroupImage: {{ .Values.images.rayHeadGroupImage | quote }}
    rayWorkerGroupImage: {{ .Values.images.rayWorkerGroupImage | quote }}
  defaultAcceleratorType: {{ .Values.defaultAcceleratorType | quote }}
  splunkConfiguration: {{ toYaml .Values.splunkConfiguration | nindent 4 }}
  storage:
    vectorDB:
      pvcName: {{ .Values.storage.vectorDB.pvcName | quote }}
      size: {{ .Values.storage.vectorDB.size | quote }}
      storageClassName: {{ .Values.storage.vectorDB.storageClassName | quote }}
{{- if .Values.gpuScheduler }}
  gpuScheduler:
{{- if .Values.gpuScheduler.nodeSelector }}
    nodeSelector: {{ toYaml .Values.gpuScheduler.nodeSelector | nindent 6 }}
{{- end }}
{{- if .Values.gpuScheduler.affinity }}
    affinity: {{ toYaml .Values.gpuScheduler.affinity | nindent 6 }}
{{- end }}
{{- if .Values.gpuScheduler.tolerations }}
    tolerations: {{ toYaml .Values.gpuScheduler.tolerations | nindent 6 }}
{{- end }}
{{- end }}
{{- if .Values.cpuScheduler }}
  cpuScheduler:
{{- if .Values.cpuScheduler.nodeSelector }}
    nodeSelector: {{ toYaml .Values.cpuScheduler.nodeSelector | nindent 6 }}
{{- end }}
{{- if .Values.cpuScheduler.affinity }}
    affinity: {{ toYaml .Values.cpuScheduler.affinity | nindent 6 }}
{{- end }}
{{- if .Values.cpuScheduler.tolerations }}
    tolerations: {{ toYaml .Values.cpuScheduler.tolerations | nindent 6 }}
{{- end }}
{{- end }}