# templates/aiplatform.yaml
{{- if .Capabilities.APIVersions.Has "v4.splunkai/v1" -}}
apiVersion: v4.splunkai/v1
kind: AIPlatform
metadata:
  name: {{ include "splunk-ai.fullname" . }}
  namespace: {{ include "splunk-ai.namespace" . }}
  labels:
    {{- include "splunk-ai.labels" . | nindent 4 }}
spec:
  volume:
    path: {{ .Values.volume.path | quote }}
    {{- if .Values.volume.endpoint }}
    endpoint: {{ .Values.volume.endpoint | quote }}
    {{- end }}
    region: {{ .Values.volume.region | quote }}
    secretRef: {{ .Values.volume.secretRef | quote }}
  {{- if .Values.serviceAccountName}}
  serviceAccountName: {{ .Values.serviceAccountName | quote }}
  {{- end }}
  features:
    {{- range .Values.features }}
    - name: {{ .name | quote }}
      serviceAccountName: {{ .serviceAccountName | quote }}
      version: {{ .version | quote }}
    {{- end }}
  sidecars:
    envoy: {{ .Values.sidecars.envoy }}
    fluentBit: {{ .Values.sidecars.fluentBit }}
    otel: {{ .Values.sidecars.otel }}
    prometheusOperator: {{ .Values.sidecars.prometheusOperator }}
  certificateRef: {{ .Values.certificateRef | quote }}
  clusterDomain: {{ .Values.clusterDomain | quote }}
  images:
    saiaImage: {{ .Values.images.saiaImage | quote }}
    weaviateImage: {{ .Values.images.weaviateImage | quote }}
    rayHeadGroupImage: {{ .Values.images.rayHeadGroupImage | quote }}
    rayWorkerGroupImage: {{ .Values.images.rayWorkerGroupImage | quote }}
  defaultAcceleratorType: {{ .Values.defaultAcceleratorType | quote }}
  splunkConfiguration: {{ toYaml .Values.splunkConfiguration | nindent 4 }}
  storage:
    vectorDB:
      pvcName: {{ .Values.storage.vectorDB.pvcName | quote }}
      size: {{ .Values.storage.vectorDB.size | quote }}
      storageClassName: {{ .Values.storage.vectorDB.storageClassName | quote }}
  gpuScheduling:
    nodeSelector: {{ toYaml .Values.gpuScheduling.nodeSelector | nindent 4 }}
    affinity: {{ toYaml .Values.gpuScheduling.affinity | nindent 4 }}
    tolerations: {{ toYaml .Values.gpuScheduling.tolerations | nindent 4 }}
  cpuScheduling:
    nodeSelector: {{ toYaml .Values.cpuScheduling.nodeSelector | nindent 4 }}
    affinity: {{ toYaml .Values.cpuScheduling.affinity | nindent 4 }}
    tolerations: {{ toYaml .Values.cpuScheduling.tolerations | nindent 4 }}
{{- end -}}
