apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "splunk-ai.serviceAccountName" . }}
  namespace: {{ include "splunk-ai.namespace" . }}
  labels:
    {{- include "splunk-ai.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
