name: OSS Scan
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  fossa-scan:
    uses: splunk/oss-scanning/.github/workflows/oss-scan.yml@main
    secrets: inherit
