name: Build and Test

on:
  pull_request: {}
  push:
    branches:
      - main
      - develop
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  prodsec-workflow:
    uses: ./.github/workflows/main-prodsec-workflow.yml
    secrets: inherit

  check-formatting:
    uses: ./.github/workflows/main-check-formatting.yml

  unit-tests:
    uses: ./.github/workflows/main-unit-tests.yml
    needs: check-formatting

  build-image:
    uses: ./.github/workflows/main-build-image.yml
    secrets: inherit
    needs: unit-tests

  vulnerability-scan:
    uses: ./.github/workflows/main-vulnerability-scan.yml
    secrets: inherit
    needs: build-image

  # smoke-tests:
  #   uses: ./.github/workflows/main-smoke-tests.yml
  #   secrets: inherit
  #   needs: vulnerability-scan
