name: Package Helm Chart
on:
  workflow_call:

jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      # Need the write permission because this job commits changes to some folders like dist
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Dotenv Action
        uses: falti/dotenv-action@d4d12eaa0e1dd06d5bdc3d7af3bf4c8c93cb5359
        id: dotenv
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.dotenv.outputs.GO_VERSION }}
      - name: Run helm chart package creation
        run: |
          helm package helm-chart/splunk-ai-operator
          cp splunk-ai-operator-${{ github.event.inputs.new_operator_version }}.tgz docs/
          mv splunk-ai-operator-${{ github.event.inputs.new_operator_version }}.tgz helm-chart/splunk-enterprise/charts
          helm package helm-chart/splunk-enterprise
          mv splunk-enterprise-${{ github.event.inputs.new_operator_version }}.tgz docs/
          helm repo index --url https://splunk.github.io/splunk-ai-operator/ docs/
