name: Pre-Release Workflow
on:
  workflow_dispatch:
    inputs:
      old_operator_version:
        description: 'OLD OPERATOR VERSION'
        required: true
      new_operator_version:
        description: 'NEW OPERATOR VERSION'
        required: true

permissions:
  contents: write

jobs:
  package-helm:
    uses: ./.github/workflows/release/package-helm.yml
    with:
      old_operator_version: ${{ github.event.inputs.old_operator_version }}
      new_operator_version: ${{ github.event.inputs.new_operator_version }}
